config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts do
	  resources :comments
  end

  root "posts#index"

  get 'admin', :to => "access#index"
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :post, presence: true
  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        # format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.html { redirect_to(:controller => 'posts', :action => 'show', :id => @comment.post_id) }
        format.json { render :show, status: :created, location: @comment }
        format.js { }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @comment = Comment.find(params[:id])
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    comment = Comment.find(params[:id])
    post_id = comment.post_id
    comment.destroy
    respond_to do |format|
      format.html { redirect_to(:controller => 'posts', :action => 'show', :id => post_id) }
      # format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body, :createdby)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
      <strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</strong><br />
      <%= comment.body %>
      <% if current_user.email.to_s == comment.createdby.to_s then %>

          <%= link_to("Edit", {:controller => 'comments', :action => 'edit', :id => comment.id}, :class => 'action edit') %>
          <%# link_to("Destroy",{:controller => 'comments', :action => 'delete', :id => comment.id}, :class => 'action delete') %>
          <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_newcommentunderpost.html.erb
	<table summary="New Comment">
		<tr>New Comment</tr>
		<tr>
			<td><%= form_for(:comment, :url => {:controller => 'comments', :action => 'create'}, :postid => @post.id, :remote => true)do |f| %>
					<%= f.hidden_field :post_id, :value => @post.id %>
					<%= f.text_area :body, :required => true %><br /><br />
                    <%= f.hidden_field :createdby, :value => current_user.email %>

				<div class="form-buttons">
					<%= submit_tag "Add Comment", :id=> "submitcomment" %>
				</div>
				<% end %>
			</td>
		</tr>
	</table>

    <!--, :remote => true-->

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment)) %>").hide();
$('#commentsection').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', controller: 'posts', action: 'show', id: @comment.post_id %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<!-- <strong>Note: </strong> Only your comments are visible to you! -->


<br />
<br />
<br />
<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.createdby %></td>
        <% if current_user.email.to_s == comment.createdby.to_s then %>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Comment', new_comment_path %>
<%= link_to '<< Go to Posts', posts_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', controller: 'posts', action: 'show', id: @comment.post_id %>